### ISSUE TITLE
Ninepatch lines after download

### ISSUE THREAD

**Issue by amirraza** [inloop/shadow4android#10]
please let me know how to hide ninepatch lines in downloading although it is hiding in preview by checking false.

**Comment by yuraj11** [comment]
Hi,
is there any reason why would you like to disable ninepatch lines in output?

**Comment by amirraza** [comment]
> Hi,
> is there any reason why would you like to disable ninepatch lines in output?

After downloading the final image and using in my XML is showing that black line too.

**Comment by fryette** [comment]
same issue

**Comment by k-sae** [comment]
Hi @amirraza,  
make sure you are keeping the extension as *.9.png so that android can know that you are using a ninepatch image and renders it properly.

**Comment by amirraza** [comment]
> Hi @amirraza,
> make sure you are keeping the extension as *.9.png so that android can know that you are using a ninepatch image and renders it properly.

Solved!
