### ISSUE TITLE
Hi, I have added some feature to adjust the padding between content and line

### ISSUE THREAD

**Issue by x000zh** [inloop/shadow4android#11]
Hi, @yuraj11 , thank you for the work.
I have added a padding setting between line and content in the advance panel, should I pull the code ?
[the commit](https://github.com/x000zh/shadow4android/commit/feed1e0850e0d120c9c5fa20e6aee827c0edb28e)

**Comment by yuraj11** [comment]
Hi,
thanks for the contribution. Could you please create pull request?

**Comment by x000zh** [comment]
ok
