### ISSUE TITLE
Are we considering supporting the generation of a line of shadow instead of a rectangle?

### ISSUE THREAD

**Issue by walterFeng** [inloop/shadow4android#15]
![image](https://user-images.githubusercontent.com/23520425/57900292-d70ca800-7892-11e9-927b-81181527df44.png)

**Comment by walterFeng** [comment]
on the side , can I set a alpha value to shadow color?

**Comment by yuraj11** [comment]
I think this is already possible, section Advanced - Side clipping - Left, Right and Bottom checked.
And about the shadow color - yes it's possible to set alpha:

![image](https://user-images.githubusercontent.com/5477518/94295038-f45e8580-ff60-11ea-98db-129972b88a34.png)

or use `rgba(0,0,0,0.78)` as value where last decimal number is alpha between 0 to 1.
