### ISSUE TITLE
would be nice if we could define transparency in shadow color

### ISSUE THREAD

**Issue by melanke** [inloop/shadow4android#5]

**Comment by melanke** [comment]
nevermind, I found it haha

**Comment by Mr-Ramzan** [comment]
@melanke  Please can you describe how?
I increased shadow Blurr value but it added padding or margin with it

**Comment by melanke** [comment]
wow I am having a time travel here hahahaha
2016?! I can't even remember using this library haha
Sorry, good luck :)

**Comment by Mr-Ramzan** [comment]
yup, there is the first time for everyone/thing
naming xyz.9.png in assets did the trick
thanks for responding 😇
