### ISSUE TITLE
is it possible to have fill overlap shadow?

### ISSUE THREAD

**Issue by kuoliangkwong** [inloop/shadow4android#6]
Hi I love this tool, but is it possible to do something like this:

![untitled](https://cloud.githubusercontent.com/assets/8188634/17178053/834e5d4e-5446-11e6-9941-69e4ab2f5bce.png)

so the fill reaches the edge. Is it possible to make an option for 4 edges as well?

**Comment by yuraj11** [comment]
Thanks.
But I am not sure about your question - can you make some comparison between your image and shadow4android result please?

**Comment by yuraj11** [comment]
Thanks.
You mean something like this? So ninepatch can be used for example in listview ? (top, bottom, middle item) ? That is good idea :+1: Am I right?
![image](https://cloud.githubusercontent.com/assets/5477518/17181354/276bda68-5420-11e6-950f-0f1320d5e242.png)

**Comment by kuoliangkwong** [comment]
yup that's right. Can be used in listview or even combination with multiple views stacking together. 

Is it going to be developed soon or it would be somewhere further in the roadmap?

**Comment by yuraj11** [comment]
Great idea, thanks. I will start working on this today or tomorrow.

**Comment by kuoliangkwong** [comment]
That's great~ Really looking forward for it 👍
