### ISSUE TITLE
How can I achieve a circular shadow? 

### ISSUE THREAD

**Issue by psydj1** [inloop/shadow4android#9]
I know it's not quite an issue but I would like to add shadow to a circular view. How can I create a 9 patch for that?.

**Comment by monsterbrain** [comment]
I think 9 patch is applicable only for square-rect type shapes. To add shadow to circular view, you need to add a custom drawable for that (read from stackoverflow), or generate a shadowed png image in gimp or photoshop.

**Comment by yuraj11** [comment]
Hi,
not possible with 9patch as mentioned by @monsterbrain .
